





























export default App;}  );    </div>      <button onClick={() => signOutRedirect()}>Sign out</button>      <button onClick={() => auth.signinRedirect()}>Sign in</button>    <div>  return (  }    );      </div>        <button onClick={() => auth.removeUser()}>Sign out</button>        <pre>Hello: {auth.user?.profile.email}</pre>      <div>    return (  if (auth.isAuthenticated) {  if (auth.error) return <div>Error: {auth.error.message}</div>;  if (auth.isLoading) return <div>Loading...</div>;  };    window.location.href = `${cognitoDomain}/logout?client_id=${clientId}&logout_uri=${encodeURIComponent(logoutUri)}`;  const signOutRedirect = () => {  const auth = useAuth();function App() {import { useAuth } from "react-oidc-context";